"""initial schema

Revision ID: 88b549786e2d
Revises: 
Create Date: 2026-03-29 11:36:11.612752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b549786e2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('dmarc_policy', sa.String(), nullable=True),
    sa.Column('spf_record', sa.String(), nullable=True),
    sa.Column('dkim_selectors', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_active'), 'domains', ['active'], unique=False)
    op.create_index('ix_domains_active_verified', 'domains', ['active', 'verified'], unique=False)
    op.create_index(op.f('ix_domains_created_at'), 'domains', ['created_at'], unique=False)
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_index('ix_domains_policy', 'domains', ['dmarc_policy'], unique=False)
    op.create_index('ix_domains_updated', 'domains', ['updated_at'], unique=False)
    op.create_index(op.f('ix_domains_verified'), 'domains', ['verified'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('dmarc_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('begin_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=False),
    sa.Column('source_email', sa.String(), nullable=True),
    sa.Column('policy', sa.String(), nullable=True),
    sa.Column('subdomain_policy', sa.String(), nullable=True),
    sa.Column('adkim', sa.String(length=1), nullable=True),
    sa.Column('aspf', sa.String(length=1), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dmarc_reports_begin_date'), 'dmarc_reports', ['begin_date'], unique=False)
    op.create_index('ix_dmarc_reports_domain_dates', 'dmarc_reports', ['domain_id', 'begin_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_domain_id'), 'dmarc_reports', ['domain_id'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_end_date'), 'dmarc_reports', ['end_date'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_id'), 'dmarc_reports', ['id'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_org_name'), 'dmarc_reports', ['org_name'], unique=False)
    op.create_index('ix_dmarc_reports_policy', 'dmarc_reports', ['policy'], unique=False)
    op.create_index('ix_dmarc_reports_processed', 'dmarc_reports', ['processed_at'], unique=False)
    op.create_index(op.f('ix_dmarc_reports_report_id'), 'dmarc_reports', ['report_id'], unique=False)
    op.create_table('user_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_domains_id'), 'user_domains', ['id'], unique=False)
    op.create_table('report_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.String(), nullable=False),
    sa.Column('dkim', sa.String(), nullable=True),
    sa.Column('spf', sa.String(), nullable=True),
    sa.Column('header_from', sa.String(), nullable=True),
    sa.Column('envelope_from', sa.String(), nullable=True),
    sa.Column('dkim_auth_details', sa.Text(), nullable=True),
    sa.Column('spf_auth_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['dmarc_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_records_disposition', 'report_records', ['disposition', 'count'], unique=False)
    op.create_index(op.f('ix_report_records_dkim'), 'report_records', ['dkim'], unique=False)
    op.create_index(op.f('ix_report_records_header_from'), 'report_records', ['header_from'], unique=False)
    op.create_index(op.f('ix_report_records_id'), 'report_records', ['id'], unique=False)
    op.create_index(op.f('ix_report_records_report_id'), 'report_records', ['report_id'], unique=False)
    op.create_index('ix_report_records_source_auth', 'report_records', ['source_ip', 'dkim', 'spf'], unique=False)
    op.create_index(op.f('ix_report_records_source_ip'), 'report_records', ['source_ip'], unique=False)
    op.create_index(op.f('ix_report_records_spf'), 'report_records', ['spf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_records_spf'), table_name='report_records')
    op.drop_index(op.f('ix_report_records_source_ip'), table_name='report_records')
    op.drop_index('ix_report_records_source_auth', table_name='report_records')
    op.drop_index(op.f('ix_report_records_report_id'), table_name='report_records')
    op.drop_index(op.f('ix_report_records_id'), table_name='report_records')
    op.drop_index(op.f('ix_report_records_header_from'), table_name='report_records')
    op.drop_index(op.f('ix_report_records_dkim'), table_name='report_records')
    op.drop_index('ix_report_records_disposition', table_name='report_records')
    op.drop_table('report_records')
    op.drop_index(op.f('ix_user_domains_id'), table_name='user_domains')
    op.drop_table('user_domains')
    op.drop_index(op.f('ix_dmarc_reports_report_id'), table_name='dmarc_reports')
    op.drop_index('ix_dmarc_reports_processed', table_name='dmarc_reports')
    op.drop_index('ix_dmarc_reports_policy', table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_org_name'), table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_id'), table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_end_date'), table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_domain_id'), table_name='dmarc_reports')
    op.drop_index('ix_dmarc_reports_domain_dates', table_name='dmarc_reports')
    op.drop_index(op.f('ix_dmarc_reports_begin_date'), table_name='dmarc_reports')
    op.drop_table('dmarc_reports')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_domains_verified'), table_name='domains')
    op.drop_index('ix_domains_updated', table_name='domains')
    op.drop_index('ix_domains_policy', table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_created_at'), table_name='domains')
    op.drop_index('ix_domains_active_verified', table_name='domains')
    op.drop_index(op.f('ix_domains_active'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
